apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    env: test
spec:
  containers:
  - name: rv
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd   # this label defined in a node
